name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-ninja

      - name: Put MSYS2_MinGW64 on PATH
        run: echo "D:/a/_temp/msys64/mingw64/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2
      - name: install crosscompiler
        run: sudo apt-get install mingw-w64

      - name: make
        run: (cd src && make)
